// Code generator for x86_64 assembly (AT&T syntax for macOS)

use crate::ast::*;
use std::collections::HashMap;

pub struct CodeGenerator {
    output: String,
    label_counter: usize,
    stack_offset: i32,
    next_stack_offset: i32,
    local_vars: HashMap<String, i32>,
    current_function: Option<String>,
}

impl CodeGenerator {
    pub fn new() -> Self {
        CodeGenerator {
            output: String::new(),
            label_counter: 0,
            stack_offset: 0,
            next_stack_offset: 0,
            local_vars: HashMap::new(),
            current_function: None,
        }
    }

    pub fn generate(&mut self, program: &Program) -> String {
        self.output.clear();

        // Output header (macOS syntax)
        self.output.push_str("    .globl _main\n\n");

        // Generate global data
        self.output.push_str("    .data\n");
        for (_var_type, name, init) in &program.global_declarations {
            self.output.push_str(&format!("{}: ", name));
            match init {
                Some(Expr::IntConst(value)) => {
                    self.output.push_str(&format!(".quad {}\n", value));
                }
                Some(Expr::CharConst(value)) => {
                    self.output.push_str(&format!(".byte {}\n", *value as i32));
                }
                _ => {
                    self.output.push_str(".quad 0\n");
                }
            }
        }
        self.output.push_str("\n");

        // Generate text section with functions
        self.output.push_str("    .text\n");

        for func in &program.functions {
            self.generate_function(func);
        }

        self.output.clone()
    }

    fn generate_function(&mut self, func: &Function) {
        self.current_function = Some(func.name.clone());
        self.stack_offset = 0;
        self.next_stack_offset = 0;
        self.local_vars.clear();

        self.output.push_str(&format!("_{}:\n", func.name));

        // Function prologue (AT&T syntax)
        self.output.push_str("    pushq %rbp\n");
        self.output.push_str("    movq %rsp, %rbp\n");

        // Allocate space for local variables
        let local_count = self.count_local_vars(&func.body);
        if local_count > 0 {
            let stack_size = ((local_count + 1) / 2) * 16; // Align to 16 bytes
            self.output.push_str(&format!("    subq ${}, %rsp\n", stack_size));
            self.stack_offset = stack_size as i32;
        }

        // Generate body
        self.generate_statement(&func.body);

        // Note: Function epilogue is generated by return statements or implicitly at end
        // We don't add it here to avoid duplication

        self.current_function = None;
    }

    fn count_local_vars(&self, stmt: &Stmt) -> usize {
        let mut count = 0;
        match stmt {
            Stmt::Declaration { .. } => count += 1,
            Stmt::Block(statements) => {
                for s in statements {
                    count += self.count_local_vars(s);
                }
            }
            Stmt::If { then_stmt, else_stmt, .. } => {
                count += self.count_local_vars(then_stmt);
                if let Some(else_s) = else_stmt {
                    count += self.count_local_vars(else_s);
                }
            }
            Stmt::While { body, .. } | Stmt::DoWhile { body, .. } => {
                count += self.count_local_vars(body);
            }
            Stmt::For { init, condition: _, update: _, body } => {
                if let Some(init_stmt) = init {
                    count += self.count_local_vars(init_stmt);
                }
                count += self.count_local_vars(body);
            }
            _ => {}
        }
        count
    }

    fn generate_statement(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Expr(expr) => {
                self.generate_expression(expr);
                self.output.push_str("    addq $8, %rsp\n"); // Discard result
            }
            Stmt::Return(opt_expr) => {
                if let Some(expr) = opt_expr {
                    self.generate_expression(expr);
                    self.output.push_str("    popq %rax\n");
                }
                self.output.push_str("    leave\n");
                self.output.push_str("    ret\n");
            }
            Stmt::Block(statements) => {
                for s in statements {
                    self.generate_statement(s);
                }
            }
            Stmt::If { condition, then_stmt, else_stmt } => {
                let else_label = self.new_label();
                let end_label = self.new_label();

                self.generate_expression(condition);
                self.output.push_str("    popq %rax\n");
                self.output.push_str("    testq %rax, %rax\n");
                self.output.push_str(&format!("    je {}\n", else_label));

                self.generate_statement(then_stmt);
                self.output.push_str(&format!("    jmp {}\n", end_label));

                self.output.push_str(&format!("{}:\n", else_label));
                if let Some(else_s) = else_stmt {
                    self.generate_statement(else_s);
                }
                self.output.push_str(&format!("{}:\n", end_label));
            }
            Stmt::While { condition, body } => {
                let start_label = self.new_label();
                let end_label = self.new_label();

                self.output.push_str(&format!("{}:\n", start_label));

                self.generate_expression(condition);
                self.output.push_str("    popq %rax\n");
                self.output.push_str("    testq %rax, %rax\n");
                self.output.push_str(&format!("    je {}\n", end_label));

                self.generate_statement(body);
                self.output.push_str(&format!("    jmp {}\n", start_label));

                self.output.push_str(&format!("{}:\n", end_label));
            }
            Stmt::DoWhile { body, condition } => {
                let start_label = self.new_label();
                let end_label = self.new_label();

                self.output.push_str(&format!("{}:\n", start_label));
                self.generate_statement(body);

                self.generate_expression(condition);
                self.output.push_str("    popq %rax\n");
                self.output.push_str("    testq %rax, %rax\n");
                self.output.push_str(&format!("    jne {}\n", start_label));

                self.output.push_str(&format!("{}:\n", end_label));
            }
            Stmt::For { init, condition, update, body } => {
                let start_label = self.new_label();
                let end_label = self.new_label();
                let update_label = self.new_label();

                if let Some(init_stmt) = init {
                    self.generate_statement(init_stmt);
                }

                self.output.push_str(&format!("{}:\n", start_label));

                if let Some(cond_expr) = condition {
                    self.generate_expression(cond_expr);
                    self.output.push_str("    popq %rax\n");
                    self.output.push_str("    testq %rax, %rax\n");
                    self.output.push_str(&format!("    je {}\n", end_label));
                }

                self.generate_statement(body);

                self.output.push_str(&format!("{}:\n", update_label));
                if let Some(update_expr) = update {
                    self.generate_expression(update_expr);
                    self.output.push_str("    popq %rax\n");
                }
                self.output.push_str(&format!("    jmp {}\n", start_label));

                self.output.push_str(&format!("{}:\n", end_label));
            }
            Stmt::Break => {
                // Simplified: we don't track loop nesting
            }
            Stmt::Continue => {
                // Simplified: we don't track loop nesting
            }
            Stmt::Declaration { var_type: _, name, init } => {
                let offset = self.allocate_stack_var(name);
                if let Some(init_expr) = init {
                    self.generate_expression(init_expr);
                    self.output.push_str("    popq %rax\n");
                    self.output.push_str(&format!("    movq %rax, {}(%rbp)\n", -offset));
                }
            }
        }
    }

    fn generate_expression(&mut self, expr: &Expr) {
        match expr {
            Expr::IntConst(value) => {
                self.output.push_str(&format!("    pushq ${}\n", value));
            }
            Expr::CharConst(value) => {
                self.output.push_str(&format!("    pushq ${}\n", *value as i64));
            }
            Expr::StringConst(_) => {
                // Simplified: just push 0 for now
                self.output.push_str("    pushq $0\n");
            }
            Expr::Identifier(name) => {
                if let Some(offset) = self.local_vars.get(name) {
                    self.output.push_str(&format!("    movq {}(%rbp), %rax\n", -offset));
                    self.output.push_str("    pushq %rax\n");
                } else {
                    // Assume it's a global variable
                    self.output.push_str(&format!("    movq {}(%rip), %rax\n", name));
                    self.output.push_str("    pushq %rax\n");
                }
            }
            Expr::BinaryOp { op, left, right } => {
                self.generate_expression(right);
                self.generate_expression(left);

                self.output.push_str("    popq %rbx\n");
                self.output.push_str("    popq %rax\n");

                match op {
                    BinaryOp::Add => self.output.push_str("    addq %rbx, %rax\n"),
                    BinaryOp::Sub => self.output.push_str("    subq %rbx, %rax\n"),
                    BinaryOp::Mul => self.output.push_str("    imulq %rbx, %rax\n"),
                    BinaryOp::Div => {
                        self.output.push_str("    xorq %rdx, %rdx\n");
                        self.output.push_str("    idivq %rbx\n");
                    }
                    BinaryOp::Mod => {
                        self.output.push_str("    xorq %rdx, %rdx\n");
                        self.output.push_str("    idivq %rbx\n");
                        self.output.push_str("    movq %rdx, %rax\n");
                    }
                    BinaryOp::Equal => {
                        self.output.push_str("    cmpq %rbx, %rax\n");
                        self.output.push_str("    sete %al\n");
                        self.output.push_str("    movzbq %al, %rax\n");
                    }
                    BinaryOp::NotEqual => {
                        self.output.push_str("    cmpq %rbx, %rax\n");
                        self.output.push_str("    setne %al\n");
                        self.output.push_str("    movzbq %al, %rax\n");
                    }
                    BinaryOp::Less => {
                        self.output.push_str("    cmpq %rbx, %rax\n");
                        self.output.push_str("    setl %al\n");
                        self.output.push_str("    movzbq %al, %rax\n");
                    }
                    BinaryOp::LessEqual => {
                        self.output.push_str("    cmpq %rbx, %rax\n");
                        self.output.push_str("    setle %al\n");
                        self.output.push_str("    movzbq %al, %rax\n");
                    }
                    BinaryOp::Greater => {
                        self.output.push_str("    cmpq %rbx, %rax\n");
                        self.output.push_str("    setg %al\n");
                        self.output.push_str("    movzbq %al, %rax\n");
                    }
                    BinaryOp::GreaterEqual => {
                        self.output.push_str("    cmpq %rbx, %rax\n");
                        self.output.push_str("    setge %al\n");
                        self.output.push_str("    movzbq %al, %rax\n");
                    }
                    BinaryOp::And => {
                        self.output.push_str("    andq %rbx, %rax\n");
                    }
                    BinaryOp::Or => {
                        self.output.push_str("    orq %rbx, %rax\n");
                    }
                    BinaryOp::BitAnd => {
                        self.output.push_str("    andq %rbx, %rax\n");
                    }
                    BinaryOp::BitOr => {
                        self.output.push_str("    orq %rbx, %rax\n");
                    }
                    BinaryOp::BitXor => {
                        self.output.push_str("    xorq %rbx, %rax\n");
                    }
                    BinaryOp::ShiftLeft => {
                        self.output.push_str("    movq %rbx, %rcx\n");
                        self.output.push_str("    shlq %cl, %rax\n");
                    }
                    BinaryOp::ShiftRight => {
                        self.output.push_str("    movq %rbx, %rcx\n");
                        self.output.push_str("    sarq %cl, %rax\n");
                    }
                }

                self.output.push_str("    pushq %rax\n");
            }
            Expr::UnaryOp { op, operand } => {
                self.generate_expression(operand);
                self.output.push_str("    popq %rax\n");

                match op {
                    UnaryOp::Negate => self.output.push_str("    negq %rax\n"),
                    UnaryOp::Not => {
                        self.output.push_str("    cmpq $0, %rax\n");
                        self.output.push_str("    sete %al\n");
                        self.output.push_str("    movzbq %al, %rax\n");
                    }
                    UnaryOp::BitNot => self.output.push_str("    notq %rax\n"),
                    UnaryOp::Deref => {
                        self.output.push_str("    movq (%rax), %rax\n");
                    }
                    UnaryOp::Address => {
                        // Simplified: assume it's a local variable
                    }
                    UnaryOp::PreInc => {
                        self.output.push_str("    incq %rax\n");
                    }
                    UnaryOp::PreDec => {
                        self.output.push_str("    decq %rax\n");
                    }
                    UnaryOp::PostInc => {
                        self.output.push_str("    movq %rax, %rbx\n");
                        self.output.push_str("    incq %rax\n");
                        self.output.push_str("    pushq %rbx\n");
                        return;
                    }
                    UnaryOp::PostDec => {
                        self.output.push_str("    movq %rax, %rbx\n");
                        self.output.push_str("    decq %rax\n");
                        self.output.push_str("    pushq %rbx\n");
                        return;
                    }
                }

                self.output.push_str("    pushq %rax\n");
            }
            Expr::Assignment { left, right } => {
                self.generate_expression(right);

                match &**left {
                    Expr::Identifier(name) => {
                        if let Some(offset) = self.local_vars.get(name) {
                            self.output.push_str("    popq %rbx\n");
                            self.output.push_str(&format!("    movq %rbx, {}(%rbp)\n", -offset));
                            self.output.push_str("    pushq %rbx\n");
                        } else {
                            // Global variable
                            self.output.push_str("    popq %rbx\n");
                            self.output.push_str(&format!("    movq %rbx, {}(%rip)\n", name));
                            self.output.push_str("    pushq %rbx\n");
                        }
                    }
                    _ => {
                        // Simplified: just pop the right side
                        self.output.push_str("    popq %rbx\n");
                        self.output.push_str("    pushq %rbx\n");
                    }
                }
            }
            Expr::Call { func, args } => {
                // Push arguments in reverse order (System V AMD64 ABI)
                for arg in args.iter().rev() {
                    self.generate_expression(arg);
                }

                match &**func {
                    Expr::Identifier(name) => {
                        self.output.push_str(&format!("    call _{}\n", name));
                    }
                    _ => {
                        self.output.push_str("    call *%rax\n");
                    }
                }

                // Clean up stack
                if !args.is_empty() {
                    self.output.push_str(&format!("    addq ${}, %rsp\n", args.len() * 8));
                }

                // Save return value
                self.output.push_str("    pushq %rax\n");
            }
            Expr::Cast { target_type: _, expr: inner } => {
                self.generate_expression(inner);
            }
        }
    }

    fn allocate_stack_var(&mut self, name: &str) -> i32 {
        let offset = self.next_stack_offset + 8;
        self.local_vars.insert(name.to_string(), offset);
        self.next_stack_offset = offset;
        offset
    }

    fn new_label(&mut self) -> String {
        let label = format!("L{}", self.label_counter);
        self.label_counter += 1;
        label
    }
}

pub fn generate(program: &Program) -> String {
    let mut generator = CodeGenerator::new();
    generator.generate(program)
}
